#pragma once

typedef enum LpwEnumKeyboardEvent
{
    LPW_ENUM_KEYBOARD_EVENT_NULL,
    LPW_ENUM_KEYBOARD_EVENT_KEY,
    LPW_ENUM_KEYBOARD_EVENT_MAX_ENUM,
}LpwEnumKeyboardEvent;

typedef enum LpwEnumKeyboardKeyEvent
{
    LPW_ENUM_KEYBOARD_KEY_EVENT_NULL    ,
    LPW_ENUM_KEYBOARD_KEY_EVENT_PRESS   ,
    LPW_ENUM_KEYBOARD_KEY_EVENT_RELEASE ,
    LPW_ENUM_KEYBOARD_KEY_EVENT_DOUBLE  ,
    LPW_ENUM_KEYBOARD_KEY_EVENT_MAX_ENUM,
}LpwEnumKeyboardKeyEvent;