#pragma once

typedef enum LpwEnumMouseWheel
{
    LPW_ENUM_MOUSE_WHEEL_NULL       ,
    LPW_ENUM_MOUSE_WHEEL_FORWARD    ,
    LPW_ENUM_MOUSE_WHEEL_BACKWARD   ,
    LPW_ENUM_MOUSE_WHEEL_LEFTWARD   ,
    LPW_ENUM_MOUSE_WHEEL_RIGHTWARD  ,
    LPW_ENUM_MOUSE_WHEEL_MAX_ENUM   ,
}LpwEnumMouseWheel;