#pragma once

typedef enum LpwEnumMouseEvent
{
    LPW_ENUM_MOUSE_EVENT_NULL,
    LPW_ENUM_MOUSE_EVENT_POS,
    LPW_ENUM_MOUSE_EVENT_WHEEL,
    LPW_ENUM_MOUSE_EVENT_BUTTON,
    //LPW_ENUM_MOUSE_EVENT_,
    LPW_ENUM_MOUSE_EVENT_MAX_ENUM,
}LpwEnumMouseEvent;

// typedef enum LpwEnumMouseEvent
// {
//     LPW_ENUM_MOUSE_EVENT_NULL               = 0,
//     LPW_ENUM_MOUSE_EVENT_POS                = 1,
//     LPW_ENUM_MOUSE_EVENT_WHEEL              = 2,
//     LPW_ENUM_MOUSE_EVENT_BUTTON_PRESS       = 4,
//     LPW_ENUM_MOUSE_EVENT_BUTTON_RELEASE     = 8,
//     LPW_ENUM_MOUSE_EVENT_BUTTON_DOUBLE      = 16,
//     LPW_ENUM_MOUSE_EVENT_BUTTON             = 
//         LPW_ENUM_MOUSE_EVENT_BUTTON_PRESS | 
//         LPW_ENUM_MOUSE_EVENT_BUTTON_RELEASE | 
//         LPW_ENUM_MOUSE_EVENT_BUTTON_DOUBLE,
//     //LPW_ENUM_MOUSE_EVENT_,
//     LPW_ENUM_MOUSE_EVENT_MAX_ENUM,
// }LpwEnumMouseEvent;

// typedef enum LpwEnumMouseButtonEvent
// {
//     LPW_ENUM_MOUSE_BUTTON_EVENT_NULL,
//     LPW_ENUM_MOUSE_BUTTON_EVENT_PRESS       = LPW_ENUM_MOUSE_EVENT_BUTTON_PRESS,
//     LPW_ENUM_MOUSE_BUTTON_EVENT_RELEASE     = LPW_ENUM_MOUSE_EVENT_BUTTON_RELEASE,
//     LPW_ENUM_MOUSE_BUTTON_EVENT_DOUBLE      = LPW_ENUM_MOUSE_EVENT_BUTTON_DOUBLE,
//     LPW_ENUM_MOUSE_BUTTON_EVENT_MAX_ENUM,
// }LpwEnumMouseButtonEvent;

typedef enum LpwEnumMouseButtonEvent
{
    LPW_ENUM_MOUSE_BUTTON_EVENT_NULL,
    LPW_ENUM_MOUSE_BUTTON_EVENT_PRESS,
    LPW_ENUM_MOUSE_BUTTON_EVENT_RELEASE,
    LPW_ENUM_MOUSE_BUTTON_EVENT_DOUBLE,
    LPW_ENUM_MOUSE_BUTTON_EVENT_MAX_ENUM,
}LpwEnumMouseButtonEvent;