#pragma once

typedef enum LpwEnumMousePosFlag
{
    LPW_ENUM_MOUSE_POS_FLAG_NULL,
    LPW_ENUM_MOUSE_POS_FLAG_CURRENT,// = LPW_ENUM_MOUSE_POS_FLAG_NULL
    LPW_ENUM_MOUSE_POS_FLAG_PREVIOUS,
    LPW_ENUM_MOUSE_POS_FLAG_DIFFERENCE,
    LPW_ENUM_MOUSE_POS_FLAG_MAX_ENUM,
}LpwEnumMousePosFlag;